# Generated by Django 4.2 on 2026-02-05 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('quota', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('event_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='event.event')),
            ],
            options={
                'db_table': 'event_sessions',
            },
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('event_organizer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_organizers',
            },
        ),
        migrations.AddIndex(
            model_name='eventsession',
            index=models.Index(fields=['event'], name='idx_event_sessions_event_id'),
        ),
        migrations.AddConstraint(
            model_name='eventsession',
            constraint=models.CheckConstraint(check=models.Q(('end_time__date', models.F('start_time__date'))), name='chk_event_session_time'),
        ),
        migrations.AddIndex(
            model_name='eventorganizer',
            index=models.Index(fields=['event'], name='idx_event_organizers_event_id'),
        ),
        migrations.AddConstraint(
            model_name='eventorganizer',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='uq_event_organizers'),
        ),
    ]
